#!/usr/bin/env python

# Shamelessly stolen from teleop_twist_keyboard in: 
# https://github.com/utexas-bwi/segbot/blob/master/segbot_bringup/scripts/teleop_twist_keyboard
# (so many layers of grabbing code)

# Based on the teleop_twist_keyboard script from brown-ros-pkg
# Original Authors: Trevor Jay
# Original License: BSD
# See https://code.google.com/p/brown-ros-pkg/ for more details

import rospy

from chassis_driver.msg import ArcadeDriveMessage

import sys, select, termios, tty

msg = """
Reading from the keyboard  and Publishing to Twist!
---------------------------
Moving around:
   u    i    o
   j    k    l
   m    ,    .
q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
anything else : stop
CTRL-C to quit
"""

moveBindings = {
		'i':(1,0),
		'o':(1,-1),
		'j':(0,1),
		'l':(0,-1),
		'u':(1,1),
		',':(-1,0),
		'.':(-1,1),
		'm':(-1,-1),
	       }

speedBindings={
		'q':(1.1,1.1),
		'z':(.9,.9),
		'w':(1.1,1),
		'x':(.9,1),
		'e':(1,1.1),
		'c':(1,.9),
	      }

def getKey():
	tty.setraw(sys.stdin.fileno())
	select.select([sys.stdin], [], [], 0)
	key = sys.stdin.read(1)
	termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
	return key

speed = 0.75
turn = 0.5

def vels(speed,turn):
	return "currently:\tspeed %s\tturn %s " % (speed,turn)

if __name__=="__main__":
    	settings = termios.tcgetattr(sys.stdin)
	
	pub = rospy.Publisher('arcade_drive', ArcadeDriveMessage)
	rospy.init_node('teleop_twist_keyboard')

	x = 0
	th = 0
	status = 0

	try:
		print msg
		print vels(speed,turn)
		while(1):
			key = getKey()
			if key in moveBindings.keys():
				x = moveBindings[key][0]
				th = moveBindings[key][1]
			elif key in speedBindings.keys():
				speed = speed * speedBindings[key][0]
				turn = turn * speedBindings[key][1]

				print vels(speed,turn)
				if (status == 14):
					print msg
				status = (status + 1) % 15
			else:
				x = 0
				th = 0
				if (key == '\x03'):
					break


			driveMsg = ArcadeDriveMessage()
			driveMsg.speed = x*speed
			driveMsg.rotation = th*turn
			pub.publish(driveMsg)

	except:
		print e

	finally:
		driveMsg = ArcadeDriveMessage()
		driveMsg.speed = 0
		driveMsg.rotation = 0
		pub.publish(driveMsg)

    		termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
